### ISSUE TITLE
would like to show the rails symbols for http status as well

### ISSUE THREAD

**Issue by deepak** [citricsquid/httpstatus.es#18]
rails can use these symbols to better name a status code
reads better
 
http://guides.rubyonrails.org/layouts_and_rendering.html#the-status-option

wanted to show it, maybe as additional info 
or would that be out of scope ?

**Comment by citricsquid** [comment]
These are already displayed on the website for some of the status codes but some are missing, however on a new version to be deployed in the coming days all status codes with a Rails HTTP Status Symbol will have that included on the status code page. Thank you for the feedback!
